### PR TITLE
[change] Replace editor store with context properties. Fix #48

### LINKED ISSUE #48: Remove Editor Store
There isn't a need for it anymore.

### PR DESCRIPTION
**Pull request by nhunzaker**
This PR removes the EditorStore, using `context` to pass down the available types. Context is an undocumented API that I learned how to use from ReactRouter. Essentially, it provides a safe way to pass down 'implied' properties from parents to children.

### CODE REVIEW

**Comment by solomonhawk** [comment]
:+1: Stability of the API isn't a concern at this stage, I assume?

**Comment by nhunzaker** [comment]
@solomonhawk I should have mentioned this, my use of `context` is temporary. There are some other pending changes and it lets me punt on passing down the available media types a parent block can create until I figure out the best way to integrate other changes.

Long term, I plan to eliminate context so that we can additionally support React 0.12

**Comment by nhunzaker** [comment]
@solomonhawk I'll make a checklist item in #45

**Comment by tommymarshall** [comment]
reading JS without `;`'s makes me so happy. :+1:

**Pull request merged**
