### PR TITLE
Added maxChildren to the BlockType documentation

### PR DESCRIPTION
**Pull request by efatsi**
I think this is how it goes. Going off [this WCS example](https://github.com/wildlife-conservation-society/wcs/blob/master/app/assets/javascripts/admin/colonel/blockTypes/index.js#L122)

### CODE REVIEW

**Comment by nhunzaker** [comment]
:heart: :+1:

**Comment by moimael** [comment]
Shouldn't this be merged ?

**Comment by nhunzaker** [comment]
Yep. I'll go ahead and do that now.

**Comment by nhunzaker** [comment]
Rebased with master.

**Pull request merged**
